# Generated by Django 5.0.6 on 2024-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation_app", "0003_automationtype_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
